services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}", "ping", "-h", "localhost", "-P", "3306"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
      start_interval: 5s
    volumes:
      - maria_volume:/var/lib/mysql
    restart: always
    secrets:
      - DB1_MASTER_PWD
      - DB1_USER
      - DB1_PWD
      - DB1_NAME
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/DB1_MASTER_PWD
      MARIADB_USER_FILE: /run/secrets/DB1_USER
      MARIADB_PASSWORD_FILE: /run/secrets/DB1_PWD
      MARIADB_ROOT_PASSWORD: ${DB1_MASTER_PWD}  
      MARIADB_DATABASE: gungeon

    ports:
      - "3306:3306"
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: pgrep php-fpm7.4
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s
      start_interval: 5s
    volumes:
      - wp_volume:/usr/share/wordpress
    restart: always
    secrets:
      - DB1_MASTER_PWD
      - DB1_USER
      - DB1_PWD
      - DB1_NAME
      - WP_MASTER_USER
      - WP_MASTER_PWD
      - WP_MASTER_EMAIL
      - WP_USER
      - WP_PWD
      - WP_EMAIL
    environment:
      DB_HOST: mariadb
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER_FILE: /run/secrets/DB1_USER
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/DB1_PWD
      WORDPRESS_DB_NAME: /run/secrets/Db1_NAME # DB_NAME should be okay if consistent
      WORDPRESS_TABLE_PREFIX: wp_
      WP_MASTER_USER_FILE: /run/secrets/WP_MASTER_USER
      WP_MASTER_PWD_FILE: /run/secrets/WP_MASTER_PWD
      WP_MASTER_EMAIL_FILE: /run/secrets/WP_MASTER_EMAIL
      WP_USR_FILE: /run/secrets/WP_USER
      WP_PWD_FILE: /run/secrets/WP_PWD
      WP_EMAIL_FILE: /run/secrets/WP_EMAIL
      DB1_MASTER_PWD_FILE: /run/secrets/DB1_MASTER_PWD
    networks:
      - inception

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wp_volume:/usr/share/wordpress
    restart: always
    networks:
      - inception

volumes:
  maria_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jverdu-r/data/maria
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/jverdu-r/data/wp

networks:
  inception:

secrets:
  DB1_MASTER_PWD:
    file: ../secrets/DB1_MASTER_PWD.txt
  DB1_USER:
    file: ../secrets/DB1_USER.txt
  DB1_PWD:
    file: ../secrets/DB1_PWD.txt
  DB1_NAME:
    file: ../secrets/DB1_NAME.txt
  WP_MASTER_USER:
    file: ../secrets/WP_MASTER_USER.txt
  WP_MASTER_PWD:
    file: ../secrets/WP_MASTER_PWD.txt
  WP_MASTER_EMAIL:
    file: ../secrets/WP_MASTER_EMAIL.txt
  WP_USER:
    file: ../secrets/WP_USER.txt
  WP_PWD:
    file: ../secrets/WP_PWD.txt
  WP_EMAIL:
    file: ../secrets/WP_EMAIL.txt
