version: "3.8"

services:
  init:
    build:
      context: ./init  # Create an 'init' directory with a Dockerfile inside
      dockerfile: Dockerfile # Name of the Dockerfile
    volumes:
      - type: bind
        source: /home/dungeonmaster/Documentos/inception  # Mount the parent directory
        target: /home/dungeonmaster/Documentos/inception
    command: /bin/true  # Keep the container running (or use a specific command)

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    depends_on:
      - init  # Depend on the init container

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
    volumes:
      - wordpress_data:/var/www/wordpress
      - wp_files:/var/www/html
    depends_on:
      - mariadb  # Depend on mariadb (which depends on init)
    networks:
      - my_network
    user: 1000:1000

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
      - wp_files:/var/www/html
      - nginx_conf:/etc/nginx/conf.d
      - ssl_certs:/etc/nginx/ssl
    depends_on:
      - wordpress  # Depend on wordpress (which depends on mariadb, which depends on init)
    networks:
      - my_network
    command: ["nginx", "-g", "daemon off;"]

networks:
  my_network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/wp_data"
  wp_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/wp_files"
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/db_data"
  nginx_conf:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/nginx_conf"
  ssl_certs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/ssl_certs"
