version: "3.8"

<<<<<<< HEAD
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network

  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-fpm
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network

  nginx:
    container_name: nginx
    image: nginx:stable
    restart: always
    depends_on:
      - wordpress
    volumes:
      - nginx_data:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - my_network
    command: [ "nginx", "-g", "daemon off;" ]

networks:
  my_network:
    driver: bridge
=======
networks:
  my_network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
  wp_files:
    driver: local
  db_data:
    driver: local
  nginx_conf:
    driver: local
  ssl_certs:
    driver: local

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
      - wp_files:/var/www/html
      - nginx_conf:/etc/nginx/conf.d
      - ssl_certs:/etc/nginx/ssl
    depends_on:
      - wordpress
    networks:
      - my_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - wordpress_data:/var/www/wordpress
      - wp_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - my_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
>>>>>>> 93a6d4e (working on ssl certicates and server config)

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/wp_data"
  db_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/db_data"
  nginx_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/dungeonmaster/Documentos/inception/nginx_conf"

