version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - type: bind
        source: /home/jverdu-r/data/db_data
        target: /var/lib/mysql
    networks:
      - my_network

  wordpress:
    container_name: wordpress
    image: wordpress:php8.2-fpm
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: "mariadb"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    volumes:
      - type: bind
        source: /home/jverdu-r/data/wp_data
        target: /var/www/html
    networks:
      - my_network

  nginx:
    container_name: nginx
    image: nginx:stable
    restart: always
    depends_on:
      - wordpress
    volumes:
      - type: bind
        source: /home/jverdu-r/data/nginx_conf
        target: /etc/nginx/conf.d
      - type: bind
        source: /home/jverdu-r/data/wp_data
        target: /var/www/html
    ports:
      - "443:443"
    networks:
      - my_network
    command: [ "nginx", "-g", "daemon off;" ]

networks:
  my_network:
    driver: bridge
