CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

USE ${MYSQL_DATABASE};

CREATE USER IF NOT EXISTS '${ADMIN_USERNAME}'@'%' IDENTIFIED BY '${ADMIN_PASSWORD}';
CREATE USER IF NOT EXISTS '${EDITOR_USERNAME}'@'%' IDENTIFIED BY '${EDITOR_PASSWORD}';

GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${ADMIN_USERNAME}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON ${MYSQL_DATABASE}.* TO '${EDITOR_USERNAME}'@'%';

FLUSH PRIVILEGES;